name: "Validate Templates"
description: "Validates a singular Coder templates using Terraform validation"

inputs:
  template:
    description: "Template name to validate"
    required: true
  template_dir:
    description: "Directory containing the template"
    required: true
  org:
    description: "Organization name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: coder/coder/.github/actions/setup-tf@main

    - name: Validate template
      shell: bash
      working-directory: ${{ inputs.template_dir }}
      run: |
        set -euo pipefail
        echo "Validating Terraform for template '${{ inputs.template }}' in org '${{ inputs.org }}' from '${{ inputs.template_dir }}'"
        terraform init
        terraform validate
